name: Deploy Updated Apps

on:
  push:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'submodules/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_apps: ${{ steps.get-changed-files.outputs.APPS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch at least 2 commits for comparison

      - name: Determine previous commit
        id: previous-commit
        run: echo "PREV_SHA=$(git rev-parse HEAD^1)" >> $GITHUB_ENV

      - name: Get changed apps
        id: get-changed-files
        run: |
          APPS=$(git diff --name-only ${{ env.PREV_SHA }} HEAD | grep -E '^apps/|^submodules/' | cut -d '/' -f2 | sort -u | jq -R -s -c 'split("\n")[:-1]')
          echo "Detected changed apps: $APPS"
          echo "APPS=$APPS" >> $GITHUB_ENV
          echo "APPS=$APPS" >> "$GITHUB_OUTPUT"

  update-kustomization:
      needs: detect-changes
      runs-on: ubuntu-latest
      if: ${{ needs.detect-changes.outputs.changed_apps != '[]' }}
      strategy:
          matrix:
            app: ${{ fromJson(needs.detect-changes.outputs.changed_apps) }}
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0  # Ensure full history for rebase
          
        - name: Get latest commit SHA
          id: vars
          run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          
        - name: Update kustomization.yml
          uses: fjogeleit/yaml-update-action@main
          with:
            valueFile: "k8s/overlays/prod/kustomization.yml"
            propertyPath: "images[?(@.name=='345594578285.dkr.ecr.eu-west-1.amazonaws.com/airwayz/${{ matrix.app }}')].newTag"
            value: ${{ env.SHA }}
            commitChange: false  # Don't commit yet
          
        - name: Commit changes
          run: |
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add k8s/overlays/prod/kustomization.yml
            git commit -m "Update image tag for ${{ matrix.app }} to ${{ env.SHA }}"
          
        - name: Pull latest changes to avoid conflicts
          run: |
            git pull --rebase origin main || (echo "Rebase failed, retrying..." && sleep 5 && git pull --rebase origin main)
          
        - name: Push changes
          run: |
            git push origin main || (echo "Push failed, retrying..." && sleep 5 && git push origin main)
          